import argparse
import os
import re
import secrets
import shutil
import socket
import subprocess
import sys
import time
import webbrowser
from pathlib import Path


INSTALL_DIR = Path(__file__).resolve().parent
DEFAULT_PORT = 8080
BASE_SHARELATEX_IMAGE = "sharelatex/sharelatex:latest"


def _supports_color():
    if os.environ.get("NO_COLOR"):
        return False
    if not hasattr(sys.stdout, "isatty") or not sys.stdout.isatty():
        return False
    if os.name == "nt" and not os.environ.get("WT_SESSION"):
        # Keep ANSI default-on for modern Windows terminals; legacy consoles may not support it.
        return True
    return True


USE_COLOR = _supports_color()
STYLE = {
    "reset": "\033[0m",
    "dim": "\033[2m",
    "bold": "\033[1m",
    "cyan": "\033[36m",
    "green": "\033[32m",
    "yellow": "\033[33m",
    "red": "\033[31m",
}


def colorize(text, color=None, bold=False, dim=False):
    if not USE_COLOR:
        return text
    parts = []
    if bold:
        parts.append(STYLE["bold"])
    if dim:
        parts.append(STYLE["dim"])
    if color:
        parts.append(STYLE[color])
    parts.append(text)
    parts.append(STYLE["reset"])
    return "".join(parts)


def section(title):
    print(colorize(f"\n== {title} ==", color="cyan", bold=True), flush=True)


def log(msg):
    if msg.startswith("[OK]"):
        print(colorize(msg, color="green", bold=True), flush=True)
        return
    if msg.startswith("[WARN]"):
        print(colorize(msg, color="yellow", bold=True), flush=True)
        return
    if msg.startswith("[ERROR]"):
        print(colorize(msg, color="red", bold=True), flush=True)
        return
    if msg.startswith("[INFO]"):
        print(colorize(msg, color="cyan"), flush=True)
        return
    print(msg, flush=True)


def run_cmd(cmd, check=False, capture=False):
    kwargs = {"check": check, "text": True}
    if capture:
        kwargs["capture_output"] = True
    return subprocess.run(cmd, **kwargs)


def check_command(cmd):
    return shutil.which(cmd) is not None


def check_docker_running():
    try:
        run_cmd(["docker", "info"], check=True)
        return True
    except Exception:
        return False


def get_compose_cmd():
    try:
        res = run_cmd(["docker", "compose", "version"], check=False, capture=True)
        if res.returncode == 0:
            return ["docker", "compose"]
    except Exception:
        pass
    if check_command("docker-compose"):
        return ["docker-compose"]
    return None


def sanitize_port(raw):
    try:
        port = int(raw)
    except Exception:
        return None
    if 1 <= port <= 65535:
        return port
    return None


def is_port_in_use(port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        return s.connect_ex(("127.0.0.1", port)) == 0


def upsert_env_var(env_path, key, value):
    line_value = f"{key}={value}"
    if not env_path.exists():
        with open(env_path, "w", encoding="utf-8") as f:
            f.write(line_value + "\n")
        return

    with open(env_path, "r", encoding="utf-8") as f:
        lines = f.read().splitlines()

    replaced = False
    out_lines = []
    for line in lines:
        if line.startswith(f"{key}="):
            out_lines.append(line_value)
            replaced = True
        else:
            out_lines.append(line)
    if not replaced:
        out_lines.append(line_value)

    with open(env_path, "w", encoding="utf-8") as f:
        f.write("\n".join(out_lines).rstrip() + "\n")


def create_env(domain, port, recreate=False, site_language="en"):
    env_path = INSTALL_DIR / "overleaf.env"
    if env_path.exists() and not recreate:
        log(".env exists. Keeping config.")
        upsert_env_var(env_path, "OVERLEAF_SITE_LANGUAGE", site_language)
        log("overleaf.env language updated.")
        return

    session = secrets.token_hex(32)
    jwt = secrets.token_hex(32)
    data = f"""# Generated by Overleaf CLI Installer
OVERLEAF_APP_NAME=Overleaf Community
OVERLEAF_SITE_URL=http://{domain}
OVERLEAF_SESSION_SECRET={session}
OVERLEAF_JWT_SECRET={jwt}
OVERLEAF_MONGO_URL=mongodb://overleaf-mongo/sharelatex
OVERLEAF_REDIS_HOST=overleaf-redis
REDIS_HOST=overleaf-redis
REDIS_PORT=6379
OVERLEAF_PORT={port}
OVERLEAF_SITE_LANGUAGE={site_language}
"""
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(data)
        if hasattr(os, "fchmod"):
            os.fchmod(f.fileno(), 0o600)
    log("overleaf.env written.")


def write_compose(port, sharelatex_image=BASE_SHARELATEX_IMAGE):
    compose_content = f"""services:
  sharelatex:
    image: {sharelatex_image}
    container_name: sharelatex
    restart: unless-stopped
    depends_on:
      - overleaf-mongo
      - overleaf-redis
    ports:
      - "{port}:80"
    links:
      - overleaf-mongo
      - overleaf-redis
    volumes:
      - ./data/sharelatex:/var/lib/overleaf
      - ./data/logs:/var/log/overleaf
    environment:
      OVERLEAF_MONGO_URL: mongodb://overleaf-mongo/sharelatex
      OVERLEAF_REDIS_HOST: overleaf-redis
      REDIS_HOST: overleaf-redis
    env_file:
      - overleaf.env

  overleaf-mongo:
    image: mongo:8.0
    container_name: overleaf-mongo
    restart: unless-stopped
    command: "--replSet overleaf"
    volumes:
      - ./data/mongo:/data/db

  overleaf-redis:
    image: redis:7
    container_name: overleaf-redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
"""
    with open(INSTALL_DIR / "docker-compose.yml", "w", encoding="utf-8") as f:
        f.write(compose_content)
    log("docker-compose.yml written.")


def generate_custom_dockerfile(dockerfile_path, include_full_texlive):
    lines = [
        f"FROM {BASE_SHARELATEX_IMAGE}",
        "",
    ]
    if include_full_texlive:
        lines += [
            "RUN set -eux; \\",
            "    YEAR=$(tlmgr --version | sed -n 's/.*version \\([0-9]\\{4\\}\\).*/\\1/p'); \\",
            "    tlmgr update --self || (tlmgr option repository https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/${YEAR}/tlnet-final && tlmgr update --self); \\",
            "    tlmgr install scheme-full; \\",
            "    tlmgr path add; \\",
            "    mktexlsr",
            "",
        ]
    with open(dockerfile_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines).rstrip() + "\n")
    log(f"Dockerfile generated: {dockerfile_path.name}")


def build_custom_sharelatex_image(image_tag, dockerfile_path):
    log(f"[INFO] Building custom image: {image_tag}")
    run_cmd(
        ["docker", "build", "-f", str(dockerfile_path), "-t", image_tag, str(INSTALL_DIR)],
        check=True,
    )
    log(f"[OK] Custom image built: {image_tag}")


def init_mongo_replica():
    log("Init Mongo (wait 10s)...")
    time.sleep(10)
    result = run_cmd(["docker", "exec", "overleaf-mongo", "mongosh", "--eval", "rs.initiate()"], capture=True)
    out = ((result.stdout or "") + (result.stderr or "")).strip()
    if "ok" in out or "already initialized" in out:
        log("[OK] Mongo replica set ready.")
    else:
        log(f"[!] Mongo init warning: {out}")


def run_tlmgr(args, check=True, stream=False):
    cmd = ["docker", "exec", "sharelatex", "tlmgr"] + args
    if stream:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        lines = []
        if proc.stdout:
            for line in proc.stdout:
                line = line.rstrip()
                if line:
                    lines.append(line)
                    log(line)
        proc.wait()
        output = "\n".join(lines)
        if check and proc.returncode != 0:
            raise RuntimeError(f"tlmgr {' '.join(args)} failed")
        return proc.returncode, output

    res = run_cmd(cmd, capture=True)
    output = ((res.stdout or "") + (res.stderr or "")).strip()
    if output:
        log(output)
    if check and res.returncode != 0:
        raise RuntimeError(f"tlmgr {' '.join(args)} failed")
    return res.returncode, output


def install_full_texlive():
    log("[INFO] Installing full TeX Live in sharelatex container...")
    log("[INFO] Step 1/3: tlmgr update --self")

    _, ver_out = run_tlmgr(["--version"], check=False)
    year_match = re.search(r"version\s+(\d{4})", ver_out)
    local_year = year_match.group(1) if year_match else None

    upd_code, upd_out = run_tlmgr(["update", "--self"], check=False, stream=True)
    if upd_code != 0:
        cross_release = (
            "older than remote repository" in upd_out
            and "Cross release updates are only supported" in upd_out
        )
        if cross_release and local_year:
            repo = f"https://ftp.math.utah.edu/pub/tex/historic/systems/texlive/{local_year}/tlnet-final"
            log(f"[WARN] Cross-release tlmgr repo detected. Switching to historic repo: {repo}")
            run_tlmgr(["option", "repository", repo], check=True)
            run_tlmgr(["update", "--self"], check=True, stream=True)
        else:
            raise RuntimeError("tlmgr update --self failed")

    log("[INFO] Step 2/3: tlmgr install scheme-full (this can take a long time)")
    run_tlmgr(["install", "scheme-full"], check=True, stream=True)
    log("[INFO] Step 3/3: tlmgr path add")
    run_tlmgr(["path", "add"], check=True, stream=True)
    log("[OK] Full TeX Live installation finished.")


def validate_prereqs():
    if not check_command("git"):
        raise RuntimeError("Git is not installed.")
    compose = get_compose_cmd()
    if not compose:
        raise RuntimeError("docker compose / docker-compose not found.")
    if not check_docker_running():
        raise RuntimeError("Docker is not responding.")
    return compose


def perform_install(port, site_language, recreate_env, reset_data, full_texlive, open_browser, profile, image_tag):
    compose = validate_prereqs()
    domain = f"localhost:{port}"
    first_time_install = not (INSTALL_DIR / "overleaf.env").exists()
    effective_full_texlive = full_texlive or (profile == "advanced")

    if is_port_in_use(port):
        log(f"[WARN] Port {port} is busy. Continuing because this may be existing Overleaf.")

    os.chdir(INSTALL_DIR)
    log(f"Using working directory: {INSTALL_DIR}")
    create_env(domain, port, recreate=recreate_env, site_language=site_language)
    sharelatex_image = BASE_SHARELATEX_IMAGE
    if profile == "advanced":
        dockerfile_path = INSTALL_DIR / "Dockerfile.overleaf.generated"
        if not full_texlive:
            log("[INFO] Advanced profile selected: Full TeX Live will be integrated into the custom Docker image.")
        generate_custom_dockerfile(dockerfile_path, include_full_texlive=effective_full_texlive)
        build_custom_sharelatex_image(image_tag, dockerfile_path)
        sharelatex_image = image_tag
    write_compose(port, sharelatex_image=sharelatex_image)

    if reset_data:
        run_cmd(compose + ["down"], check=False)
        data_dir = INSTALL_DIR / "data"
        if data_dir.exists():
            shutil.rmtree(data_dir, ignore_errors=True)
            log("[INFO] Removed ./data")

    run_cmd(compose + ["down"], check=True)
    run_cmd(compose + ["up", "-d"], check=True)
    init_mongo_replica()

    if effective_full_texlive and profile != "advanced":
        install_full_texlive()

    app_url = f"http://{domain}"
    open_url = f"{app_url}/launchpad" if (first_time_install or reset_data) else app_url
    log("[OK] Installation completed.")
    log(f"Access: {app_url}")
    if open_url.endswith("/launchpad"):
        log(f"[INFO] Opening first-time setup: {open_url}")
    if open_browser:
        webbrowser.open(open_url)


def perform_repair(port, site_language, recreate_env, full_texlive, profile, image_tag):
    compose = validate_prereqs()
    domain = f"localhost:{port}"
    effective_full_texlive = full_texlive or (profile == "advanced")
    os.chdir(INSTALL_DIR)
    log(f"Using working directory: {INSTALL_DIR}")
    create_env(domain, port, recreate=recreate_env, site_language=site_language)
    sharelatex_image = BASE_SHARELATEX_IMAGE
    if profile == "advanced":
        dockerfile_path = INSTALL_DIR / "Dockerfile.overleaf.generated"
        if not full_texlive:
            log("[INFO] Advanced profile selected: Full TeX Live will be integrated into the custom Docker image.")
        generate_custom_dockerfile(dockerfile_path, include_full_texlive=effective_full_texlive)
        build_custom_sharelatex_image(image_tag, dockerfile_path)
        sharelatex_image = image_tag
    write_compose(port, sharelatex_image=sharelatex_image)
    run_cmd(compose + ["up", "-d", "--force-recreate", "sharelatex"], check=True)
    if effective_full_texlive and profile != "advanced":
        install_full_texlive()
    log("[OK] Configuration repaired.")


def action_update_images():
    compose = validate_prereqs()
    os.chdir(INSTALL_DIR)
    run_cmd(compose + ["pull"], check=True)
    run_cmd(compose + ["up", "-d"], check=True)
    log("[OK] Images updated and services restarted.")


def action_compose_simple(subcmd):
    compose = validate_prereqs()
    os.chdir(INSTALL_DIR)
    if subcmd == "start":
        run_cmd(compose + ["start"], check=True)
        log("[OK] Server started.")
    elif subcmd == "stop":
        run_cmd(compose + ["stop"], check=True)
        log("[OK] Server stopped.")
    elif subcmd == "restart":
        run_cmd(compose + ["restart"], check=True)
        log("[OK] Server restarted.")


def users_list():
    js = (
        "const dbx=db.getSiblingDB('sharelatex');"
        "dbx.users.find({}, {email:1,_id:0}).sort({email:1}).forEach(u=>{ if(u.email){ print(u.email) } });"
    )
    res = run_cmd(["docker", "exec", "overleaf-mongo", "mongosh", "--quiet", "--eval", js], capture=True)
    if res.returncode != 0:
        raise RuntimeError(((res.stdout or "") + (res.stderr or "")).strip())
    out = [l.strip() for l in (res.stdout or "").splitlines() if l.strip()]
    if not out:
        log("[INFO] No users found.")
    else:
        print(colorize(f"Found {len(out)} user(s):", bold=True))
        for idx, email in enumerate(out, start=1):
            print(f"  {idx:>2}. {email}")


def users_delete(email):
    safe_email = email.replace("\\", "\\\\").replace("'", "\\'")
    js = (
        "const dbx=db.getSiblingDB('sharelatex');"
        f"const email='{safe_email}';"
        "const user=dbx.users.findOne({email:email},{_id:1,email:1});"
        "if(!user){print('NOT_FOUND');quit(0)};"
        "const proj=dbx.projects.deleteMany({owner_ref:user._id}).deletedCount;"
        "const usr=dbx.users.deleteOne({_id:user._id}).deletedCount;"
        "print('DELETED_USER='+usr);"
        "print('DELETED_PROJECTS='+proj);"
    )
    res = run_cmd(["docker", "exec", "overleaf-mongo", "mongosh", "--quiet", "--eval", js], capture=True)
    out = ((res.stdout or "") + (res.stderr or "")).strip()
    if res.returncode != 0:
        raise RuntimeError(out)
    if "NOT_FOUND" in out:
        log(f"[INFO] User not found: {email}")
        return
    m = re.search(r"DELETED_PROJECTS=(\d+)", out)
    projects_deleted = int(m.group(1)) if m else 0
    log(f"[OK] User deleted: {email} | Deleted projects: {projects_deleted}")


def preflight(port):
    status = {
        "git": check_command("git"),
        "compose": get_compose_cmd() is not None,
        "docker": check_docker_running(),
        "port_free": (port is not None and not is_port_in_use(port)),
    }
    section("Preflight")
    rows = [
        ("Git", status["git"]),
        ("Compose", status["compose"]),
        ("Docker", status["docker"]),
        (f"Port {port}", status["port_free"]),
    ]
    for name, ok in rows:
        mark = colorize("OK", color="green", bold=True) if ok else colorize("FAIL", color="red", bold=True)
        print(f"{name:<12} : {mark}")


def build_parser():
    p = argparse.ArgumentParser(
        description="Overleaf CE CLI installer/controller",
        formatter_class=argparse.RawTextHelpFormatter,
        epilog=(
            "Examples:\n"
            "  python install_overleaf_cli.py install --port 666 --site-language de\n"
            "  python install_overleaf_cli.py install --profile advanced --image-tag overleaf-sharelatex:custom\n"
            "  python install_overleaf_cli.py users list\n"
            "  python install_overleaf_cli.py users delete --email user@example.com"
        ),
    )
    sub = p.add_subparsers(dest="cmd", required=False)

    def add_common_install_flags(sp):
        sp.add_argument("--port", type=int, default=DEFAULT_PORT, help="Local port (default: 8080)")
        sp.add_argument("--site-language", default="en", help="Default site language (e.g. en,de,fr,es,it,pt)")
        sp.add_argument("--profile", choices=["basic", "advanced"], default="basic", help="Installation profile")
        sp.add_argument("--image-tag", default="overleaf-sharelatex:custom", help="Custom image tag (advanced profile)")
        sp.add_argument(
            "--full-texlive",
            action="store_true",
            help="Install full TeX Live via tlmgr (automatic with --profile advanced)",
        )

    s_install = sub.add_parser("install", help="Install/reinstall Overleaf stack")
    add_common_install_flags(s_install)
    s_install.add_argument("--recreate-env", action="store_true", help="Recreate overleaf.env with new secrets")
    s_install.add_argument("--reset-data", action="store_true", help="Remove local data before install")
    s_install.add_argument("--no-open", action="store_true", help="Do not open browser after completion")

    s_repair = sub.add_parser("repair", help="Rewrite config and recreate sharelatex")
    add_common_install_flags(s_repair)
    s_repair.add_argument("--recreate-env", action="store_true", help="Recreate overleaf.env with new secrets")

    sub.add_parser("update-images", help="Pull latest images and restart services")
    sub.add_parser("start", help="Start services")
    sub.add_parser("stop", help="Stop services")
    sub.add_parser("restart", help="Recreate/restart sharelatex")

    s_pre = sub.add_parser("preflight", help="Run prerequisite checks")
    s_pre.add_argument("--port", type=int, default=DEFAULT_PORT, help="Port to test")

    s_users = sub.add_parser("users", help="User management")
    users_sub = s_users.add_subparsers(dest="users_cmd", required=True)
    users_sub.add_parser("list", help="List users")
    u_del = users_sub.add_parser("delete", help="Delete user and owned projects")
    u_del.add_argument("--email", required=True, help="User email")
    sub.add_parser("interactive", help="Start interactive menu")

    return p


def prompt_text(label, default=None, validator=None, allow_empty=False):
    while True:
        suffix = f" [{default}]" if default not in (None, "") else ""
        raw = input(f"{label}{suffix}: ").strip()
        if raw == "" and default is not None:
            raw = str(default)
        if raw == "" and allow_empty:
            return raw
        if raw == "":
            print("Value is required.")
            continue
        if validator and not validator(raw):
            print("Invalid value. Please try again.")
            continue
        return raw


def prompt_yes_no(label, default=False):
    yn = "Y/n" if default else "y/N"
    while True:
        raw = input(f"{label} ({yn}): ").strip().lower()
        if raw == "":
            return default
        if raw in ("y", "yes"):
            return True
        if raw in ("n", "no"):
            return False
        print("Please answer with y or n.")


def prompt_choice(label, options, default):
    opts = "/".join(options)
    while True:
        raw = input(f"{label} ({opts}) [{default}]: ").strip().lower()
        if raw == "":
            raw = default
        if raw in options:
            return raw
        print(f"Choose one of: {', '.join(options)}")


def run_interactive():
    section("Interactive Mode")
    print("Choose an action:")
    actions = [
        ("install", "Install"),
        ("repair", "Repair config"),
        ("update-images", "Update images"),
        ("start", "Start containers"),
        ("stop", "Stop containers"),
        ("restart", "Restart containers"),
        ("preflight", "Run preflight checks"),
        ("users-list", "List users"),
        ("users-delete", "Delete user"),
        ("exit", "Exit"),
    ]
    for i, (_, label) in enumerate(actions, start=1):
        print(f"  {i:>2}. {label}")

    while True:
        raw = input("Select number: ").strip()
        if raw.isdigit():
            idx = int(raw)
            if 1 <= idx <= len(actions):
                action = actions[idx - 1][0]
                break
        print("Invalid selection.")

    if action == "exit":
        print("Bye.")
        return

    if action in ("start", "stop", "restart"):
        action_compose_simple(action)
        return
    if action == "update-images":
        action_update_images()
        return
    if action == "preflight":
        port_raw = prompt_text("Port", default=str(DEFAULT_PORT), validator=lambda v: sanitize_port(v) is not None)
        preflight(sanitize_port(port_raw))
        return
    if action == "users-list":
        users_list()
        return
    if action == "users-delete":
        users_list()
        email = prompt_text("Email to delete")
        users_delete(email)
        return

    # install / repair wizard
    port_raw = prompt_text("Port", default=str(DEFAULT_PORT), validator=lambda v: sanitize_port(v) is not None)
    port = sanitize_port(port_raw)
    site_language = prompt_text("Site language", default="en")
    profile = prompt_choice("Profile", ["basic", "advanced"], default="basic")
    image_tag = "overleaf-sharelatex:custom"
    if profile == "advanced":
        image_tag = prompt_text("Custom image tag", default=image_tag)
        full_texlive = True
        log("[INFO] Advanced profile selected: Full TeX Live will be integrated automatically.")
    else:
        full_texlive = prompt_yes_no("Install full TeX Live", default=False)

    recreate_env = prompt_yes_no("Recreate overleaf.env", default=False)

    if action == "install":
        reset_data = prompt_yes_no("Reset local data before install", default=False)
        open_browser = prompt_yes_no("Open browser when done", default=True)
        perform_install(
            port=port,
            site_language=site_language,
            recreate_env=recreate_env,
            reset_data=reset_data,
            full_texlive=full_texlive,
            open_browser=open_browser,
            profile=profile,
            image_tag=image_tag,
        )
    else:
        perform_repair(
            port=port,
            site_language=site_language,
            recreate_env=recreate_env,
            full_texlive=full_texlive,
            profile=profile,
            image_tag=image_tag,
        )


def main():
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.cmd in (None, "interactive"):
            run_interactive()
            return
        if args.cmd == "install":
            section("Install")
            port = sanitize_port(args.port)
            if port is None:
                raise RuntimeError("Invalid port. Must be 1..65535")
            perform_install(
                port=port,
                site_language=args.site_language,
                recreate_env=args.recreate_env,
                reset_data=args.reset_data,
                full_texlive=args.full_texlive,
                open_browser=(not args.no_open),
                profile=args.profile,
                image_tag=args.image_tag,
            )
        elif args.cmd == "repair":
            section("Repair")
            port = sanitize_port(args.port)
            if port is None:
                raise RuntimeError("Invalid port. Must be 1..65535")
            perform_repair(
                port=port,
                site_language=args.site_language,
                recreate_env=args.recreate_env,
                full_texlive=args.full_texlive,
                profile=args.profile,
                image_tag=args.image_tag,
            )
        elif args.cmd == "update-images":
            section("Update Images")
            action_update_images()
        elif args.cmd in ("start", "stop", "restart"):
            section(f"Container {args.cmd.title()}")
            action_compose_simple(args.cmd)
        elif args.cmd == "preflight":
            port = sanitize_port(args.port)
            preflight(port)
        elif args.cmd == "users":
            section("Users")
            if args.users_cmd == "list":
                users_list()
            elif args.users_cmd == "delete":
                users_delete(args.email)
            else:
                parser.error("Unknown users subcommand")
        else:
            parser.error("Unknown command")
    except Exception as e:
        print(colorize(f"[ERROR] {e}", color="red", bold=True), file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
